# Generated by Django 3.1.1 on 2020-11-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(choices=[('1', '一年级'), ('2', '二年级'), ('3', '三年级'), ('4', '四年级'), ('5', '五年级'), ('6', '六年级'), ('7', '七年级'), ('8', '八年级'), ('9', '九年级')], max_length=10, verbose_name='年级')),
            ],
            options={
                'verbose_name': '学生年级',
                'verbose_name_plural': '学生年级',
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradename', models.CharField(choices=[('1', '一班'), ('2', '二班'), ('3', '三班'), ('4', '四班'), ('5', '五班'), ('6', '六班')], max_length=10, verbose_name='年级')),
            ],
            options={
                'verbose_name': '学生班级',
                'verbose_name_plural': '学生班级',
            },
        ),
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('studentid', models.AutoField(primary_key=True, serialize=False, verbose_name='学号')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='学生姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('image', models.ImageField(default='default.png', upload_to='head_image/%Y/%m', verbose_name='用户头像')),
                ('mobile', models.CharField(max_length=11, verbose_name='监护人手机号码')),
                ('StudentClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentclass', verbose_name='年级信息')),
                ('StudentGrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentgrade', verbose_name='班级信息')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
