# Generated by Django 3.1.1 on 2020-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinformation',
            options={'verbose_name': '学生信息', 'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='gradename',
            field=models.CharField(choices=[('1', '一班'), ('2', '二班'), ('3', '三班'), ('4', '四班'), ('5', '五班'), ('6', '六班'), ('7', '七班'), ('8', '八班')], max_length=10, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='image',
            field=models.ImageField(default='default.png', upload_to='head_image/%Y/%m', verbose_name='学生头像'),
        ),
    ]
