# Generated by Django 3.1.1 on 2020-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInformation',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False, verbose_name='课程ID')),
                ('courseName', models.CharField(max_length=20, verbose_name='课程名')),
            ],
        ),
    ]
