# Generated by Django 3.1.1 on 2020-11-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseinformation',
            options={'verbose_name': '课程信息', 'verbose_name_plural': '课程信息'},
        ),
    ]
