# Generated by Django 3.1.1 on 2020-11-26 08:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20201124_1630'),
        ('students', '0002_auto_20201124_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('classscore', models.FloatField(default=0, max_length=6, verbose_name='成绩')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinformation', verbose_name='课程ID')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentinformation', verbose_name='学生ID')),
            ],
            options={
                'verbose_name': '课程成绩信息',
                'verbose_name_plural': '课程成绩信息',
            },
        ),
    ]
