# Generated by Django 3.1.1 on 2020-11-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201124_1630'),
        ('students', '0002_auto_20201124_1627'),
        ('classResults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classresult',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinformation', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='classresult',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentinformation', verbose_name='学生'),
        ),
    ]
