# Generated by Django 3.1.1 on 2020-11-29 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201124_1627'),
        ('courses', '0002_auto_20201124_1630'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classResults', '0002_auto_20201126_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClassInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentclass', verbose_name='年级信息')),
                ('StudentGrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentgrade', verbose_name='班级信息')),
                ('classInformation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courseinformation', verbose_name='学科信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '教师班级信息',
                'verbose_name_plural': '教师班级信息',
            },
        ),
    ]
